- name: Install and start Apache on all servers
  hosts: all
  become: yes
  tasks:
    - name: Install Apache (httpd)
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start apache
      ansible.builtin.service:
        name: httpd
      status: started
      enebled: yes
# test
