- name: Install and start Apache on all servers
  hosts: all
  become: yes
  tasks:
    - name: Install Apache (httpd)
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start apache (httpd)
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Install vim (text editor)
      ansible.builtin.yum:
        name: vim
        state: present
######これはテストです。実施日:20250505
